import { z } from "zod";
import { Schema } from "../../src/index.ts";

/** Untrusted application input. Unlike an LLM decision schema, ordinary Zod can parse free text. */
export const shipmentInput = z
  .object({
    id: z.string().regex(/^[A-Z0-9_-]{1,64}$/),
    orderId: z.string().min(1).max(64),
    carrier: z.string().min(1).max(80),
    daysLate: z.number().int().min(0).max(365),
    priority: z.enum(["standard", "priority"]),
    notes: z.string().min(1).max(4_000),
  })
  .strict();
export type Shipment = z.output<typeof shipmentInput>;

export const actions = [
  "request_carrier_update",
  "verify_address",
  "inspect_damage",
  "manual_investigation",
] as const;
export const actionSchema = z.enum(actions);
export type Action = z.output<typeof actionSchema>;

/** Finite semantic decisions. Output transforms remain pure: no database writes or notifications. */
export const assessmentSchema = z
  .object({
    reason: z.enum(["delay", "address", "damage", "unknown"]).meta({
      description: "What is the primary reported shipment exception?",
      questions: {
        options: {
          delay: "Slow or stalled delivery",
          address: "Missing or incorrect address information",
          damage: "Reported damaged parcel or contents",
          unknown: "The notes do not establish a reason",
        },
      },
    } satisfies Schema.Metadata),
    urgent: z
      .boolean()
      .describe("Do the notes describe an exception requiring prompt operator attention?"),
    impact: z
      .number()
      .min(0)
      .max(2)
      .register(Schema.registry, {
        kind: "score",
        levels: ["Minor inconvenience", "Delivery impaired", "Delivery impossible"],
        instructions: "How seriously does this exception impair delivery?",
      }),
  })
  .transform((value) => ({
    ...value,
    proposedAction: (
      {
        delay: "request_carrier_update",
        address: "verify_address",
        damage: "inspect_damage",
        unknown: "manual_investigation",
      } as const
    )[value.reason],
  }));
export type Assessment = z.output<typeof assessmentSchema>;
export const SCHEMA_VERSION = "delivery-assessment-v1";

/** An operator's explicit command, never generated by the LLM. */
export const reviewInput = z.discriminatedUnion("decision", [
  z
    .object({
      reviewId: z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),
      expectedVersion: z.number().int().positive(),
      decision: z.literal("approve"),
      action: actionSchema,
      reviewer: z.string().min(1).max(80),
      note: z.string().min(1).max(1_000),
    })
    .strict(),
  z
    .object({
      reviewId: z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),
      expectedVersion: z.number().int().positive(),
      decision: z.literal("dismiss"),
      reviewer: z.string().min(1).max(80),
      note: z.string().min(1).max(1_000),
    })
    .strict(),
]);
export type Review = z.output<typeof reviewInput>;
export const notificationSchema = z
  .object({
    eventId: z.string().min(1).max(160),
    caseId: shipmentInput.shape.id,
    action: actionSchema,
  })
  .strict();

/** Operational HTTP errors have safe messages; model/transport details are not sent to clients. */
export class DeskError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
  }
}
